# Generated by Django 6.1 on 2026-08-22 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('origin', models.CharField(choices=[('dar_es_salaam', 'Dar es Salaam'), ('mwanza', 'Mwanza'), ('arusha', 'Arusha'), ('dodoma', 'Dodoma'), ('mbeya', 'Mbeya'), ('tanga', 'Tanga'), ('zanzibar', 'Zanzibar'), ('moshi', 'Moshi'), ('irelia', 'Irelia'), ('mbay', 'Mbeya'), ('kigoma', 'Kigoma'), ('shinyanga', 'Shinyanga')], max_length=50)),
                ('destination', models.CharField(choices=[('dar_es_salaam', 'Dar es Salaam'), ('mwanza', 'Mwanza'), ('arusha', 'Arusha'), ('dodoma', 'Dodoma'), ('mbeya', 'Mbeya'), ('tanga', 'Tanga'), ('zanzibar', 'Zanzibar'), ('moshi', 'Moshi'), ('irelia', 'Irelia'), ('mbay', 'Mbeya'), ('kigoma', 'Kigoma'), ('shinyanga', 'Shinyanga')], max_length=50)),
                ('pickup_date', models.DateField()),
                ('delivery_deadline', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10000)])),
                ('status', models.CharField(choices=[('pending', 'Pending Bids'), ('assigned', 'Assigned to Driver'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cargo', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10000)])),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='cargo.cargo')),
            ],
            options={
                'unique_together': {('cargo', 'bidder')},
            },
        ),
    ]
