# Generated by Django 6.1 on 2026-08-22 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='delivery_deadline',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='weight',
        ),
        migrations.AddField(
            model_name='cargo',
            name='dropoff_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='cargo',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
